version: 2
jobs:
  build:
    branches:
      ignore:
        - master
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{ checksum "package.json" }}
            - node-deps-v1-{{ .Branch }}
            - node-deps-v1
      - run:
          command: |
            git config --global user.email "jiwoo.link@gmail.com"
            git config --global user.name "constmoon"
      - run:
          command: npm install
      - run:
          command: npm run deploy
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/project/node_modules